FROM eclipse-temurin:21-jdk-jammy as build

WORKDIR /tmp
COPY --link docker/deps-list.info .
RUN jlink --add-modules $(cat deps-list.info) \
      --strip-debug --compress zip-6 \
      --no-header-files --no-man-pages \
      --output slimjvm

FROM ubuntu:noble

ENV JAVA_HOME /opt/java/openjdk/bin/java
ENV PATH $JAVA_HOME/bin:$PATH
COPY --from=build /tmp/slimjvm $JAVA_HOME
