name: Build Application Image
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      DOCKER_REGISTRY_URL: ghcr.io
      IMAGE_REPOSITORY: ghcr.io/lgalabov/mn-dbslim
      BASE_IMAGE_TAG: ghcr.io/lgalabov/temurin-21.slim:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Commit Hash
        uses: prompt/actions-commit-hash@v3
        id: commit

      - name: Get Next Version
        uses: ietf-tools/semver-action@v1
        id: semver
        with:
          token: ${{ github.token }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        env:
          BUILD_ENV: CI
          IMAGE_TAG_SEMVER: ${{ env.IMAGE_REPOSITORY }}:${{ steps.semver.outputs.nextStrict }}
          IMAGE_TAG_COMMIT: ${{ env.IMAGE_REPOSITORY }}:${{ steps.commit.outputs.short }}
          IMAGE_TAG_LATEST: ${{ env.IMAGE_REPOSITORY }}:latest
        run: ./gradlew optimizedDockerPush --no-daemon

#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.semver.outputs.next }}
#          generateReleaseNotes: true
#          allowUpdates: true
#          draft: false
#          makeLatest: true
