name: Build Base Image
on:
  workflow_dispatch:
    inputs:
      tag-version:
        description: 'Optimized base image version'
        default: '1.0.0'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      DOCKER_REGISTRY_URL: ghcr.io
      IMAGE_REPOSITORY: ghcr.io/lgalabov/temurin-21.slim
      IMAGE_VERSION: ${{ github.event.inputs.tag-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Base Image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile-base
          push: true
          tags: >-
            ${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_VERSION }},
            ${{ env.IMAGE_REPOSITORY }}:latest
